### ISSUE TITLE
Could `createPersister` have a chance to save inconsistent state?

### ISSUE THREAD

**Issue by igrayson** [rt2zz/redux-persist#104]
Hi team,

I've been reading through, to get a handle on `getStoredState` and `createPersister` usage.

While reading through https://github.com/rt2zz/redux-persist/blob/master/src/createPersistor.js#L7, I think I came up with a story where the debounce mechanic could cause us to persist inconsistent state -- i.e., persisted state which never existed in the redux store itself.

I'm particularly looking at where the debouncer only saves the 'oldest' unsaved subkey (https://github.com/rt2zz/redux-persist/blob/master/src/createPersistor.js#L51) at each interval.

Timeline:

1) Store updates `a: foo1`. State: `{ a: 'foo1' }`.
2) `createPersister` persists `reduxPersist:a = foo1`.
3) Store updates `a: foo2`. State: `{ a: 'foo2' }`.
4) Store updates `b: bar1`. State: `{ a: 'foo2', b: 'bar1' }`. 
5) Store updates `a: foo3`. State: `{ a: 'foo3', b: 'bar1' }`.
6) `createPersister` persists `reduxPersist:a = foo3`.
7) Exit.

Once we start up again, `getStoredState` will load `{ a: 'foo3' }`, which _was never_ a state of our redux store.

**Comment by rt2zz** [comment]
This is correct, we start with the oldest unsaved key, but we continue to process the queue every debounce interval (FIFO) until there are no more unsaved keys. If there is a crash/exit before the queue is finished processing you can end up with partially saved state.

Any thoughts on how this can be remedied or reduced?

**Comment by igrayson** [comment]
I believe we'd have the same vulnerability, even if we didn't debounce, and saved each [modified] sub-hash, on each store update -- simply because saving to the store is asynchronous and not guaranteed.

I suspect the only way to guarantee consistency, while also allowing the store to be saved in sub-hashes for performance, is to provide transactionality. Some non-trivial refactoring could be done to `createPersister` to support an expanded interface for our [storage backend](https://github.com/rt2zz/redux-persist#storage-backends) that implements transactions.

I believe unexpected crashes, or unexpected (by the application) exits will be more common for react-native mobile applications, which are more frequently and randomly force-stopped by the OS.

As an aside, do you know of any other similar projects? After reading through this repo and [redux-storage](https://github.com/michaelcontento/redux-storage), I think we prefer the abstractions of this one. Once/if we hit up against inconsistencies due to this race condition, we'd be looking to provide transactionality to `createPersister`, along with a [sqlite storage backend](https://github.com/andpor/react-native-sqlite-storage).

**Comment by rt2zz** [comment]
AFAIK redux-storage and redux-persist are the only two reasonable options right now. 

I doubt that most redux applications would have an issue with the substate of each reducer being out of sync in practice. If the state is so strongly linked it would probably make sense to keep it within the same reducer.

I am definitely open to supporting transactions. In my naive imagination I expect the biggest challenge will be: how to decide when to store *old* state in order to complete a transaction versus when to store new state and effectively begin a new transaction before the old one is complete. e.g.
1) state changes `{a: 1, b: 1}`
2) persist `reduxPersist:a = 1` (b still in persist queue)
3) state changes `{a: 2, b: 2}`
4) ? do we store `b: 1` and complete the transaction or begin a new transaction and store `b: 2`.

For simplicity I expect we should store `b: 1` (i.e. the old state) and finish the transaction. In the worst case this would result in twice as many save operations, but it would avoid the potential for never ending transactions and keep the mental model simple.

**Comment by rt2zz** [comment]
@igrayson agreed that is simplest, but would fail pretty horribly if an application has repeated state updates that occur faster than the total transaction completion time, as no transaction will ever be completed.

**Comment by igrayson** [comment]
Not sure I agree. Depending on the store, and our configuration, we could see different behaviors:

1. Large debounce, high completion time: transaction1 finishes before transaction2 begins. Correct behavior.

2. No/small debounce, high completion time: transaction1 doesn't finish until after transaction2 begins. The debounce mechanism could detect this and wait until the next 'bounce' to attempt transaction2. This indicates that the app should increase debounce configuration. We could also let this pass through, if the application expected "bursty" behavior and still wanted a small debounce (sqlite as a backend, for example, could correctly serialize this backlog).

Ref (2) above: I've had an engineer tell me that RN asynclocalstorage _always_ introduces a ~200ms delay (to reinforce the 'async' idea? ;). Given this, it's possible for our transactionless persistence today is already hitting this behavior when we use a small debounce.
