### ISSUE TITLE
How to purge the local storage efficiently when the state shape is updated ?

### ISSUE THREAD

**Issue by antoinerey** [rt2zz/redux-persist#118]
Hello !

First of all, sorry if questions are not meant to be posted as issues, but I didn't find anywhere any guidelines.

I'm building a dynamic application, and I'm struggling to find a robust way to purge the local storage when some modifications are applied to the redux state shape.

Let's say in a version 1, that my application state looks like this : 

```js
const state = {
  users: Array<User>,
  posts: Array<Post>,
}
```

Some weeks / months later, I need to update the state to look like this :

```js
const updatedState = {
  users: Array<User>,
  pages: Array<Page>, // This part is renamed
}
```

Obviously, after the update, the state stored in local storage won't work with the new shape. So, I'm looking for a way to purge the state, efficiently.

**A solution**

I could store within the application state a version number, matching the state shape. So, my states could become : 

```js
const state = {
  version: 1,
  users: Array<User>,
  posts: Array<Post>,
}

const updatedState = {
  version: 2,
  users: Array<User>,
  pages: Array<Page>, // This part is renamed
}
```

Now, I can just compare both versions and purge the local storage if the versions do not match.

While working (I think), this approach has some cons :

1. I have to remember to bump the state version on updates.
2. I'm not only destroying the updated part, but the whole state.

**Did you have similar issue ? If yes, how did you solve them ?**

Thanks a lot ;)

**Comment by rt2zz** [comment]
Yes I think a version number is the correct approach. I would recommend [redux-persist-migrate](https://github.com/wildlifela/redux-persist-migrate), this is the solution I came up with for the same problem after much tinkering. Feedback welcome!

**Comment by prithsharma** [comment]
@antoinerey Thanks for the example above. I was thinking through similar use cases for my app when I stumbled upon this issue. I have a basic doubt on this discussion about when is a change in state shape really an issue.
Considering your example above, let's assume the old and new states were as follows:-
```
oldState = {
  users: Array<User>,
  posts: Array<Post>,
};
```
```
newState = {
  users: Array<User>,
  pages: Array<Page>,
};
```
I think it is safe to assume that the reducers above would have `initialState`s defined. Let those be:-
```
oldInitialState = {
  users: [],
  posts: [],
};
```
```
newInitialState = {
  users: [],
  pages: [],
};
```

Now considering the case when there is no migration logic and the basic `autoRehydrate` method is used to rehydrate from `localStorage`. After the update, when the `REHYDRATE` action is dispatched for the first time, it would shallow merge the `localState` onto the `initialState` which would give the following state
```
rehydratedState = {
  users: Array<User>,
  posts: Array<Post>, # this is stale
  pages: [],
}
```

Any code that would be accessing `state.pages` would be written in a way that it can work with the `initiateState`(since the cache isn't available always, it must have been written that way). Any code that was using `state.posts` doesn't exist now. So in most cases, this would work as if the `posts` store was purged, or as if this is the first time app is opened. As long as that is the case and one doesn't need anything advanced like maintaining cache across store shape changes, why do we really need a migration strategy?
One way I can think of is that for example if the `Post` object was internally changed and the code is expecting it to be of certain shape without placing appropriate checks - then you would want that the `posts` store is migrated well.
Just wanted to know if my understanding is correct. I am almost sure that I must be missing something here and the need for something like `redux-persist-migrate` is much more than what I wrote above - please correct me if that's the case, just want to understand the right use case.

**Comment by prithsharma** [comment]
@antoinerey Thanks for the example above. I was thinking through similar use cases for my app when I stumbled upon this issue. I have a basic doubt on this discussion about when is a change in state shape really an issue.
Considering your example above, let's assume the old and new states were as follows:-
```
oldState = {
  users: Array<User>,
  posts: Array<Post>,
};
```
```
newState = {
  users: Array<User>,
  pages: Array<Page>,
};
```
I think it is safe to assume that the reducers above would have `initialState`s defined. Let those be:-
```
oldInitialState = {
  users: [],
  posts: [],
};
```
```
newInitialState = {
  users: [],
  pages: [],
};
```

Now considering the case when there is no migration logic and the basic `autoRehydrate` method is used to rehydrate from `localStorage`. After the update, when the `REHYDRATE` action is dispatched for the first time, it would shallow merge the `localState` onto the `initialState` which would give the following state
```
rehydratedState = {
  users: Array<User>,
  posts: Array<Post>, # this is stale
  pages: [],
}
```

Any code that would be accessing `state.pages` would be written in a way that it can work with the `initiateState`(since the cache isn't available always, it must have been written that way). Any code that was using `state.posts` doesn't exist now. So in most cases, this would work as if the `posts` store was purged, or as if this is the first time app is opened. As long as that is the case and one doesn't need anything advanced like maintaining cache across store shape changes, why do we really need a migration strategy?
One way I can think of is that for example if the `Post` object was internally changed and the code is expecting it to be of certain shape without placing appropriate checks - then you would want that the `posts` store is migrated well.
Just wanted to know if my understanding is correct. I am almost sure that I must be missing something here and the need for something like `redux-persist-migrate` is much more than what I wrote above - please correct me if that's the case, just want to understand the right use case. 
@rt2zz @antoinerey any ideas?
