### ISSUE TITLE
Question about working with redux-devtools

### ISSUE THREAD

**Issue by lexun** [rt2zz/redux-persist#14]
Does this commit indicate that you were able to get these working together or just that it wasn't an issue worth investing in at that point? https://github.com/rt2zz/redux-persist/commit/340ff7a5cef1b0f345a704b8401272a655a7e436#diff-04c6e90faac2675aa89e2176d2eec7d8L87

**Comment by rt2zz** [comment]
haha, well strictly speaking it is working with redux-devtools, I have successfully run them both together.

That said I think there is probably more investigation required, e.g. what happens if you are rehydrating immutable data. If you run into any issues let me know, I will be happy to figure out fixes.

**Comment by lexun** [comment]
Great, I will probably be rehydrating immutable data soon so I'll let you know if there are issues. Thanks!
