### ISSUE TITLE
Webpack outputs .css when uses redux-persist@4.0.0-alpha*

### ISSUE THREAD

**Issue by octaviogb** [rt2zz/redux-persist#187]
Hi, 

I'm using alpha6 with react-boilerplate, but, when  I build it, webpack outputs my main as .css.

I've found out that if I remove "es", getting away with lodash-es, everything goes well.

So, any help? Is lodash-es really needed?

**Comment by marvinhagemeister** [comment]
@octaviogb  Thanks for reporting this bug. I'm unsure at which part of the stack the problem appears. Could be the webpack config, could be a problem with our setup, or it could be something entirely else. I'd love to help you track down the root cause.

Can you post your webpack config or if you can a tiny sample repository where we can reproduce this behaviour?

**Comment by rt2zz** [comment]
afaict this is unrelated.
