### ISSUE TITLE
handling REHYDRATE in middleware causes state to not be persisted

### ISSUE THREAD

**Issue by noisegrrrl** [rt2zz/redux-persist#231]
I need to get access to the action fired when the store is being rehydrated to handle sockets namespaces and connect users to the right namespace on refresh.
Problem is, if I do this, the state is not persisted, I'm not sure why and I'm not sure how to handle this as a result.

**Comment by rt2zz** [comment]
how are you accessing the action? You have a few options here:

- use a effect handler like redux-saga for redux-observable to listen and act on the REHYDRATE event.
- use `getStoredState` and `createPersistor` individually instead of `persistStore` to gain more fine grained control.

That said I am not sure why accessing the action would stop persistence as you mentioned. Are you getting errors?

**Comment by th0th** [comment]
Can you be trying to handle REHYDRATE action in one of your reducers that needs to be updated the very same action? I tried the same then came across this issue when looking for a solution my problem.

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
