### ISSUE TITLE
[docs] skipRestore alternative

### ISSUE THREAD

**Issue by Andarist** [rt2zz/redux-persist#307]
Im seeing that [this option got deprecated](https://github.com/rt2zz/redux-persist/blob/e89e62ec627c4a41a193f259a7dbadcdff392d06/src/persistStore.js#L12) and `createPersistor` is suggested as alternative, but honestly - I have no idea how to achieve the same result with this. Would be great if such use case would get its place in the docs. If you provide me a sample of the code I might provide a PR with description etc of the use case.

**Comment by rt2zz** [comment]
Implementation depends on your use case, i.e. why do you want to skip restore?

If for example you want to use the stored state as initialState rather than relying on REHYDRATE action you can do this:

```
import {getStoredState, createPersistor} from 'redux-persist'

getStoredState(persistConfig, (err, restoredState) => {
  const store = createStore(reducer, restoredState)
  const persistor = createPersistor(store, persistConfig)
})
```

getStoredState: finds all redux-persist keys, and then fetches them and reconstructs the state object.

createPersistor: creates a stateful object that listens for changes to redux state and efficiently writes said state to storage.

**Comment by Andarist** [comment]
I rather would like to listen for `REHYDRATE` but dispatch (could be implicitly) it conditionally. If possible I would like to keep `createStore` process sync, as its easier to instantiate other things without wrapping in promises etc.

**Comment by rt2zz** [comment]
`getStoredState` is always async, which means the closest we could get to something like being sync is to wrap it in an async function and await the result.

As for conditional persistence you can do something like
```js
import {getStoredState, createPersistor} from 'redux-persist'

async function bootstrap () {

  let restoredState = await getStoredState(persistConfig)
  const store = createStore(reducer, restoredState)
  const persistor = createPersistor(store, persistConfig)
  
  ReactDOM.render(
    <App />,
    document.getElementById('root')
  )
}

bootstrap()

**Comment by Andarist** [comment]
Thanks for the help, I think I understand now more. I'l look later if there is a place I could add such example in the docs.

Although I seriously consider writing some simple tiny lib for doing all of this myself as my needs are really basic and your lib is quite a robust one. Great work on it anyway 👏 Just feeling a little bit that its an overkill for my use case. Will live in our production env for quite some time though as for sure such refactor is not a pressing issue for us ;)

**Comment by rt2zz** [comment]
at this point `skipRestore` is an undocumented feature - its just hanging around because I am not keen on breaking backwards. I think at this point a deprecation message is the way to go.

For sure, I am working hard to keep this lib light an robust, and hopefully easy enough to use that there is no need to roll your own (simple as that may be). redux persist ideally obviates the need to each dev to think about things like handling safari private mode, inefficient serialize etc.

I have some things planned for the future that should make the most common use cases much simpler 👍 Thanks for all the great feedback, its always welcome!

**Comment by Andarist** [comment]
so here I am again :P I wanted to add the snippet as docs example, but now I've realised that it still doesnt cover my desired use case. Basically I would like to skip conditionally dispatching `REHYDRATE` action. You example focuses on conditional providing of `initialState`

**Comment by rt2zz** [comment]
well, I suppose there may be a few ways to handle this - including possibly an api update. What is the condition you are deciding on? I have two thoughts:

1. `persistStore` is fairly simple under the hood and could be replicated custom in your app easily enough. The key lines you care about are https://github.com/rt2zz/redux-persist/blob/master/src/persistStore.js#L23-L32 which basically does 3 things
  - getStoredState
  - fire REHYDRATE (should be easy enough to roll in some condition logic)
  - createPersistor
2. Using https://github.com/rt2zz/redux-persist-state-manager instead of autoRehydrate, we could easily add a predicate config that would decide wether or not to handle the incoming REHYDRATE action.

**Comment by Andarist** [comment]
My scenario is to read the condition from the query string, which means in general any initial source. I would prefer not to save this info in the store itself to skip rehydration in REHYDRATE's branches of reducer to keep this part of the app agnostic from the fact that rehydration might not happen.

Option number 1 seems reasonable, however quite a duplication of already implemented stuff, just to do this 1 thing.

**Comment by Andarist** [comment]
I went with first option, but it rly feels like quite a duplication of code. The neat thing is I could rewrite it to sync handling as my target is web only, but it will ofc drive away from original implementation in time which is undesired. 


Not worth documenting I think, but will post here my snippet, maybe somebody will find it useful.
```javascript
import { createPersistor, getStoredState } from 'redux-persist'
import { REHYDRATE } from 'redux-persist/constants'

const config  = ... // app-specific config
const shouldRestore = ... // app-specific logic

export default function persistStore(store) {
	const persistor = createPersistor(store, config)
	persistor.pause()

	if (shouldRestore) {
		getStoredState(config, (err, restoredState) => {
			store.dispatch({
				type: REHYDRATE,
				payload: restoredState,
			})
			persistor.resume()
		})
	} else {
		persistor.resume()
	}

	return persistor
}
```

**Comment by jptaranto** [comment]
That's very useful, thanks @Andarist!

**Comment by skizzo** [comment]
@Andarist , how would you implement your solution with `redux-persist` v6.x?

**Comment by Andarist** [comment]
@skizzo not sure, im not up to date with current APIs
