### ISSUE TITLE
Rehydrate Action after Async Action

### ISSUE THREAD

**Issue by jorexe** [rt2zz/redux-persist#347]
Hi, i'm building a React Native app and i'm using redux-persist to initialize my redux state. Then i update my data using an API to sync my server data. My problem is that the Hydratation ocurrs after the sync and my server data never gets update. I don't want to black list that data, because i want to use that data if do not have internet connection.

Thanks you

**Comment by ankit90anand** [comment]
You should sync your server data in rehydration callback.

This will ensure your store are updated with the localy stored data.

**Comment by zacacollier** [comment]
@jorexe componentWillReceiveProps could be useful here. I was troubleshooting an issue where one of my components rendered before redux-persist had finished rehydrating the store.

Assuming you're syncing the server with data from your component's props (via mapStateToProps), you could do something like what I did:
```javascript
  ...
  componentWillReceiveProps(nextProps) {
    nextProps && (this.props = { ...nextProps });
  }
  ...
```

If you need even more fine-grained control, then you can leverage [componentWillMount()](https://facebook.github.io/react/docs/react-component.html#componentwillmount), since it will fire immediately before `render()` is called.

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
