### ISSUE TITLE
onComplete not a function

### ISSUE THREAD

**Issue by michaelcuneo** [rt2zz/redux-persist#410]
Hey guys, this isn't an error anymore, but I needed to post my solution because it took me so long to work out how stupid I was... 

persistStore(store, { blacklist: ['route'] }, { storage: localForage });
persistStore(store, { blacklist: ['route'], storage: localForage });

The top line caused an error, onComplete is not a function. The bottom line did not cause an error.

I've seen this issue crop up all over the internet in relation to redux-persist/redux-persist-immutable... 
So there it is. the simple removal of }, { and having the blacklist and storage in the one section of ES6.

**Comment by rt2zz** [comment]
right, storage is part of the config which is the second argument. Do you have any suggestions for how to avoid this?

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.

I think I've had this issue bite me pretty hard before with other JS libraries. I view it as a weakness in JavaScript the language. I think there are ways to catch this if we knew it was very common in a certain area.

The other way to avoid user from having this problem is to change the API to accept only a params object. i.e.
```js
persistStore({
  store: store,
  blacklist: ['route'],
  storage: localForage,
});
```
but I'm not sure it's worth this project implementing a change like this to work around a weakness in the JavaScript language.
