### ISSUE TITLE
stateReconciler question

### ISSUE THREAD

**Issue by Noitidart** [rt2zz/redux-persist#425]
I am using v4. I have a key in my store called `files`, its shape is like this:

```
{
    files: {
        1: { data: base64_data_here }
    }
}
```

My goal is to modify redux-persist so that it creates a file for each entry in this files key, and only if the reference of `files[i]` changes. `stateReconciler` is currently creating a file per main key in the store correct? So it is writing all entries in my `files` object everytime any entry changes. Is it possible to accomplish my goal of writing to file each subkey, and only if reference changes?

**Comment by rt2zz** [comment]
right, the logic to operate first order keys is pretty hard baked: https://github.com/rt2zz/redux-persist/blob/master/src/createPersistor.js#L39-L63

I have been thinking in v5 about adding some concept of "partition keys" which could solve what you are describing but to date it is only a thought.

To answer your question directly I think you have three options:
1. write a custom persistence solution for your app
2. put your files in an entirely separate redux store, then redux-persist@4 will work as you desire out of the box
3. upgrade to redux-persist@5, write custom getStoredState and createPersistoid implementations that store/fetch based on partition rules, and update persistReducer to take these methods as custom config options (https://github.com/rt2zz/redux-persist/blob/v5/src/persistReducer.js#L23)

The reason (3) would be best implemented as a config override is because it will require the storage engine have a `getAllKeys` method, and furthermore take a non-trivial amount of code that we do not want to burden simpler implementations with.

**Comment by Noitidart** [comment]
Thank you sir for such a in-depth reply!! I will start researching v5 now. By chance if it's non-trivial for you (< 10min) could I get a spoon feed? Haha Only if you have time, else you have given me tons already with such an amazing reply. I will start researching right away. Would you like me to close this topic?

**Comment by Noitidart** [comment]
I was going for the (3) route, I got it v5 implemented but struggling with getStoredState and createPersistoid, apologies there, any help from anyone would be so appreciated!

**Comment by Noitidart** [comment]
So i have been working with v5 today and I found that all data is saved as a serialized string in `persist:primary`.

So now whenever anything changes, even outside of the `files` key, it will end up serializing/unserializing all the base64 data of the files which can be a lot. Is there anyway to make it do it like v4, where it was seperate entry per key, like { reduxPersist:counter:3 } a file per key? (then i would break up the `files` entry into sub keys/values)

**Comment by Noitidart** [comment]
Crap struggled with this for awhile. I'm getting issues. I can give a solution with async transform, if transform gives me argument (storage). Will try that direction now.

**Comment by Noitidart** [comment]
Actually, becuase in v5, storage is mandatory, we don't need to pass `storage` as arg to transforms, they can just export from their store file, and import it into their transform.

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.

@Noitidart Note there is an outstanding PR for async transforms being considered:
PR: https://github.com/rt2zz/redux-persist/pull/360
Issue: https://github.com/rt2zz/redux-persist/issues/303
