### ISSUE TITLE
[v5] API Stable ?

### ISSUE THREAD

**Issue by jbrodriguez** [rt2zz/redux-persist#477]
Ok, I've switched to v5.

I managed the REHYDRATE action manually per reducer in v4 and did 

```
switch (action.type)
case REHYDRATE:
  if (action.payload.settings)
```

but now payload can be undefined, so I changed it to

```
switch (action.type)
case REHYDRATE:
  if (action.payload && action.payload.settings)
```
no big deal.

On the other hand, I'm having problems with purge:

![image](https://user-images.githubusercontent.com/1305422/31132206-d95d2e92-a821-11e7-98d0-8bbdddfa0ce8.png)

This is how I'm invoking the flow

```
const rootReducer = combineReducers({
	env,
	settings,
	nav,
	model,
})

const config = {
	key: 'primary',
	storage: AsyncStorage,
	throttle: 1000,
	blacklist: ['env', 'nav'],
	debug: true,
}

const reducer = persistReducer(config, rootReducer)

const configureStore = callback => {
	const sagaMiddleware = createSagaMiddleware()
	const initialState = undefined

	const composeEnhancers = __DEV__ ? window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose : compose

	const enhancer = composeEnhancers(
		applyMiddleware(sagaMiddleware),
		// other store enhancers if any
	)

	const store = createStore(reducer, initialState, enhancer)

	sagaMiddleware.run(sagas)

	persistStore(store, {}, callback).purge()

	return store
}
```

Any idea about this error ?

Everything else worked as per the instructions and in my case stored stated was reduced to about half in size. 👍 

Just wondering if the api is considered stable at this point (noticed you added autoRehydrate recently).

**Comment by rt2zz** [comment]
This was a small oversight: I added the ability to nest persisted reducers, but I forgot that combine reducers yells if it finds unexpected state. Now fixed in rc.5 https://github.com/rt2zz/redux-persist/commit/42766d246442ce3328505741d1308ed87a99ec4d

I would say that the present api is unlikely to change, **but**
1. small bugs and edge cases are likely to be found and be fixed
2. likely to add a `persistor.pause()` method
3. currently considering support for async transforms

Thank you for helping test. We just added autoRehydrate config boolean to support the case where the default state reconciliation is not appropriate. I am not yet sure if in this case there should be an option to provide an alternate state reconciler via config or if instead the suggested usage will be as you have it where you implement a custom `case REHYDRATE` statement. LMK if you have opinions.

**Comment by jbrodriguez** [comment]
Glad it helped.

I don't have strong opinions about autoRehydrate, what I have found is you do need some manual handling as your state evolves and you start adding fields over time, so each reducer has the best notion of what to do, when rehydrating (that's why I use the REHYDRATE action to set this up).

**Comment by rt2zz** [comment]
is now 👍
