### ISSUE TITLE
V5 Uncaught SyntaxError: Unexpected token import because of using import

### ISSUE THREAD

**Issue by mauron85** [rt2zz/redux-persist#488]
Some ES files are referencing dependencies via imports:

redux-persist/es/storage/index.js
```
import createWebStorage from './createWebStorage';
```

redux-persist/es/integration/react.js
```
import React, { PureComponent } from 'react'; // eslint-disable-line import/no-unresolved
```

When webpack babel-loader is configured not to include files from node_modules this will lead to client side error:

```
Uncaught SyntaxError: Unexpected token import
```

Temporal fix is to include `/node_modules\/redux-persist/` path to babel-loader includes array in your project. But I think ES variants has to be properly built with imports declaration replaced by AMD/UMD definitions.

**Comment by rt2zz** [comment]
the es build is intended to have es6 imports, primarily because that allows for tree shaking. I expect that webpack should handle the es6 modules without any custom configuration, so the fact that you are getting this error I would say is unexpected. What version of webpack are you using?

A short term fix is to import from the lib dir (all commonjs modules). I am not a webpack expert, but I suspect the issue is somewhere in the webpack config or version. FWIW redux-persist works out of the box with webpack with no custom includes for me on multiple projects.

**Comment by mauron85** [comment]
@rt2zz 
In that particular project I'm using ancient webpack 1.5.

**Comment by rt2zz** [comment]
honestly I am not sure, from what I am reading webpack should understand es6 modules. But if your goal is simply to get babel to transform away the es6 modules, you are better off using the lib build which has already taken care of that.

**Comment by mauron85** [comment]
lib build is exactly what I'm looking for. I was not seeing it somehow.
