### ISSUE TITLE
Problem with redux-thunk

### ISSUE THREAD

**Issue by mania25** [rt2zz/redux-persist#505]
Hi, i've got the problem implementing redux-persist with redux-thunk, i've got the following error when i want to call async action (http request using axios)

![screen shot 2017-10-25 at 23 23 24](https://user-images.githubusercontent.com/7329402/32010274-8df8ef38-b9db-11e7-8797-4bb5121b8689.png)

Here is my configureStore.js code:

https://gist.github.com/mania25/04a55aaa8ca000dc2a261db215424cd5

here my DeviceReducers.js code:

https://gist.github.com/mania25/0901af2d94144ddf5418901bfb7637f8

here's my DeviceAction.js:

https://gist.github.com/mania25/5e7549e34d54e317b93af22bdf518628

the problem gone when i use redux store without redux-persist, need your help please, thank you

**Comment by rt2zz** [comment]
the problem is that you are returning persistor from configureStore, you probably either want to return store *or* return both `{ store, persistor }`. Make sure you give store to react-redux Provider, as well as anything else that needs redux store. Persistor will only be used for purging and PersistGate.

**Comment by mania25** [comment]
okay, thank you for your answer, it solved now, i did'nt know that persistor was not a must to export, because it was not explained in documentation, i just only see the example without knowing why there is persistor variable declared in the example
