### ISSUE TITLE
[V5] Cannot edit reducer after persisted

### ISSUE THREAD

**Issue by hoangdoan267** [rt2zz/redux-persist#506]
I try to add more states to my reducer
For example
Before
`const initialState = {
  recentList: [],
  historyList: [],
}`

After
`const initialState = {
  recentList: [],
  historyList: [],
  watchList: [],
  downloaded: []
}`

I found my states: watchList and downloadedList were 'undefined' though another states working normally after persisted. 
I used:
```
electron: "~1.6.2",
react: "^15.6.1",
react-redux": "^5.0.6",
redux-persist": "^5.0.1"

```
Thanks for supporting me.

**Comment by rt2zz** [comment]
I am assuming you have persistReducer at the top level and are using combineReducers? The basic problem here is that you are expecting rehydration to merge 2 levels deep of your state tree, while redux-persist by default only shallow merges 1 level deep. The plan is to make this extensible via the `stateReconciler` config. Here is for example the default 1 level deep reconciler: https://github.com/rt2zz/redux-persist/blob/master/src/stateReconciler/autoMergeLevel1.js

Note most of that is just dev sanity checks, the real reconciliation is just these lines https://github.com/rt2zz/redux-persist/blob/master/src/stateReconciler/autoMergeLevel1.js#L61-L79

So ya, I think a hypothetical `autoMergeLevel2` stateReconciler would solve your use case. Question is, is there some cleaner way to expose this? e.g. this is typically the desired behavior when used with combineReducers, but not otherwise. So we could ship something like `combineAndPersistReducers`.

Open to thoughts on how to best solve this problem.
