### ISSUE TITLE
[v5] Export state reconcilers to allow custom persistReducer implementations instead of using persistCombineReducers

### ISSUE THREAD

**Issue by echoes221** [rt2zz/redux-persist#560]
Hey!

First off, loving the new V5 API! Nice work!

We're currently working on a project that provides a `createStore` like interface to the UI Library that has baked in persistence (using `redux-persist` v4) and custom `redux-offline`-like behaviour. To keep separation of concerns we do as much of that behind the scenes as possible with the main library only needing our `createStore()` and they don't need to concern themselves with further implementation than a standard redux setup would be + a few extras (blacklists etc).

We'd like to upgrade but using `persistCombineReducers` is a no go as that adds further setup/complexity to the main library. `persistCombineReducers` uses `redux`'s `combineReducers` and `autoMergeLevel2` behind the scenes if you don't pass in `config.stateReconciler` and passes on to `persistReducer`.

The solution for us would be to just use `persistReducer` and in stateReconciler ourselves but that uses `autoMergeLevel1` by default, not `autoMergeLevel2` which by the looks of things is required at root and writing our own state reconciler is out of the picture at the moment.

The proposal would be to export `redux-persist`'s state reconcilers (`autoMergeLevel1/2`) to be able to use them for custom use cases like ours with `persistReducer` so the setup would look a little something like this: 

```javascript

import { persistStore, persistReducer, autoMergeLevel2 } from 'redux-persist'
import { createStore, compose } from 'redux';
import localForage from 'localforage';

function createPersistStore(
  rootReducer,
  initialState,
  enhancers = [],
  blacklist = [],
) {
  const config = {
    key: 'root',
    storage: localForage,
    blacklist,
    stateReconciler: autoMergeLevel2
  };

  const store = createStore(
    persistReducer(config, rootReducer),
    initialState,
    compose(...enhancers),
  );

  persistStore(store);

  return store;
}
```
Or you could specify which reconciler you want with a string (e.g. 'v1', 'v2') and have `redux-persist` do the switching in the background.

We currently handle v4's implementation behind the scenes adding `autoRehydrate` etc into compose.

If you're game I'd be more than happy to do the work to export the state reconcilers out for use in custom use cases like ours.

Cheers!

**Comment by rt2zz** [comment]
Great, really excited to hear about alternative usage like this! With v5 comes a lot more power, and unfortunately that also means more choice. I tried to make it so that the default implementation was still dead simple, but that there were enough extension points to do clever and creative things while still benefiting from the underlying architecture and ecosystem.

So... with that said I think using persistReducer + autoMergeLevel2 is completely reasonable. Right now that can be done via a deep import `import autoMergeLevel2 from 'redux-persist/lib/stateReconciler/autoMergeLevel2`. Your suggestion it seems is to export this from the main module as well. I will have to think about this - I do not want to complicate the api for what is an implementation detail to most users, nor do I want to make your usecase less ergonomic.

**Comment by echoes221** [comment]
The flexibility is great that's for sure. 
I don't mind doing a deep import - you mention it in the docs for `hardSet` too. Just worried if that ends up a little bit brittle going forwards. Anything that can be used alongside the setup/config in `redux-persist`, even auxiliary pieces (a la `constants`) should possibly be exported as an object (e.g. `reconcilers {}`. Just my two cents anyway.

Happy enough to do the deep import which will allow mimicking the `normal` behaviour anyway :)

**Comment by echoes221** [comment]
Closing, thanks for the help.
