### ISSUE TITLE
[V5] How to get redux-persist working cross tabs

### ISSUE THREAD

**Issue by gocard** [rt2zz/redux-persist#569]
What would be the way to get V5 working cross tabs with local storage?  I tried calling dispatch on store and also persistor with {type: REHYDRATE} when the 'storage' event is fired, but that doesn't seem to trigger anything.

**Comment by rt2zz** [comment]
the simplest implementation would be to setup a localstorage listener (a la redux-persist-crosstab), then when change is detected, do something like 
```js
let state = await getStoredState(persistConfig)
store.dispatch({
  type: REHYDRATE,
  key: persistConfig.key,
  payload: state,
})
```

In order to make this full functional and released in redux-persist-crosstab@5 I think we would need to do the following:
1. check the changed key to make sure it matches the persistConfig
1. implement some sort of locking / cancellation so that multiple syncs do not compete
2. ensure that this will not trigger a infinite loop of rehydrates
3. add `rehydrate` method to persistor, so as to avoid manually creating the action shape

There might be other approaches as well but this seems to be the most comprehensive approach.

**Comment by gocard** [comment]
That worked.  Thanks, and thanks for your work on this library!

**Comment by TSMMark** [comment]
@gocard I'm glad you got it working! Do you still have that code and would you mind contributing it? https://github.com/rt2zz/redux-persist-crosstab/issues/15#issuecomment-347390657

If you don't have time for a formal PR I might take a shot at it later this week, but anything you could share in the meantime would be fantastic

**Comment by damianobarbati** [comment]
Yes @gocard, would you mind making a PR or share current code you used you achieve the feature? 
Not sure if @TSMMark did ever get a chance to give a stab at this?

And Thanks for the effort guys!

**Comment by TSMMark** [comment]
@damianobarbati 

> @TSMMark referenced this issue in rt2zz/redux-persist-crosstab on Dec 13, 2017
> v5 compat https://github.com/rt2zz/redux-persist-crosstab/pull/17
