### ISSUE TITLE
PersistGate does not open

### ISSUE THREAD

**Issue by j-o-d-o** [rt2zz/redux-persist#654]
I am using the PersistGate and it just shows the loading screen and seems to have some issue rehydrating, no errors. 

This is my store.js code:
```javascript
import { createStore, applyMiddleware } from 'redux';
import { persistStore, persistCombineReducers } from 'redux-persist';
import { AsyncStorage } from 'react-native';
// reducers
import auth from './../screens/auth/auth.reducer';

   
const config = {
  key: 'root',
  storage: AsyncStorage,
  version: 1
} 
 
const reducer = persistCombineReducers(config, {
  auth
})
  
export default function configureStore () {
  let store = createStore(reducer);  
  let persistor = persistStore(store);

  return { persistor, store };
}
```

this is my app.js code (entry point of app):
```javascript
import React from 'react';
import { PersistGate } from 'redux-persist/lib/integration/react';
import { Provider } from 'react-redux';
import configureStore from './redux/store';
import LoadingScreen from './screens/loading/loading.screen';
import RegisterScreen from './screens/auth/register.screen';
import DrawerNav from './drawer_nav';


export default class App extends React.Component {
    constructor(props) {
        super(props);

        this.onBeforeLift = this.onBeforeLift.bind(this);

        const { persistor, store } = configureStore();
        this.persistor = persistor;
        this.store = store;

        this.state = {
            showAuth: true
        }
    }

    onBeforeLift = () => {
        // Check if there is already a user token an deterimine this.state.showAuth
    }

    render() {
        return (
            <Provider store={this.store}>
                <PersistGate
                    loading={<LoadingScreen />}
                    onBeforeLift={() => this.onBeforeLift()}
                    persistor={this.persistor}>
                    {this.showAuth ?
                        <RegisterScreen />
                        :
                        <DrawerNav />
                    }
                </PersistGate>
            </Provider>
        );
    }
}
```

any idea what the issue is, or is it a bug?

**Comment by j-o-d-o** [comment]
Probably same issue as here: #603

**Comment by j-o-d-o** [comment]
Adding this to app.js fixes it:
```javascript
    componentDidMount() {
        this.persistor.dispatch({ type: REHYDRATE });
    }
```

Rehydrate action is never dispatched by react-persist. Is this intended? If yes, it would be nice to have it in the documentation (at least I could not find anything).

**Comment by runeogod** [comment]
Had the same problem as you, personally i didnt need to add a dispatch in my didMount.

Try replacing your AsyncStorage in your store by storage

import storage from 'redux-persist/es/storage'; // default: localStorage if web, AsyncStorage if react-native

Also , check that your export reducer does not have combineReducer, because here you are using persistCombineReducers that already do the job .

**Comment by j-o-d-o** [comment]
using combineReducer throws an error (I was stuck there before for a while too ; ) ). 
I will try to import storage from redux-persists. Thx for the hint.

**Comment by runeogod** [comment]
If you have same issue as me and success to resolve it , would you answer to my post ? 

https://github.com/rt2zz/redux-persist/issues/649

Thanks !

**Comment by j-o-d-o** [comment]
@runeogod has take a while sry. But using `import storage from 'redux-persist/es/storage';` worked. Now i don't need to rehydrate on componentDidMount(), thanks ; )

**Comment by costagolub** [comment]
@j-o-d-o The issue is closed but I think it's not fixed completely. Maybe it makes sense to open it again. 
Observing the same issue. The rehydate action doesn't emit after navigating to some page or just after refreshing the app several times I got the infinite loader on PersistGate and doesn't call rehydrate ever. I have to kill the process and restart the android emulator to make it work again. 

I tried solutions from this topic and some related ones but nothing works for me. Is anyone continue to struggle with the same issue? Any ideas what can be wrong?

**Comment by DeepaSriramRR** [comment]
If the issue is only seen while refreshing app, try this in configureStore:

export const store = createStore(persistedReducer)
export const persistor = persistStore(store)

export default () => {
  return { store, persistor }
}

This way the store and persistor are created exactly once.

**Comment by yamankatby** [comment]
SOLVED! Make sure to have at least one persist reducer.
