### ISSUE TITLE
PersistGate: animate loading component

### ISSUE THREAD

**Issue by wachunei** [rt2zz/redux-persist#655]
Hi, is there a way I can animate loading component, I know I can start an animation on life cycle events such as componentDidMount, but is there a way I can set up any other transition? or wait for it to be finished before lifting the gate?

Thanks!

**Comment by klasver** [comment]
Did you find yourself already any technics ? I am searching for something similar. I did an application fade in on reHydrated = true in v4 but searching for something similar with v5 persistGate.

**Comment by wachunei** [comment]
@klasver I did exactly the same, in that case it seems like the best alternative is to not use PersistGate and render a component that renders a splash screen before hydration (checking state._persist.rehydrated) and then animate and render main navigation component.

**Comment by klasver** [comment]
@wachunei Thank you for your quick reply. Do you have any examples? Did you also use the configureStore function in a store file? Looking forward!

**Comment by rt2zz** [comment]
right if you want to animate loading away that is probably going to require some custom connections (ala https://github.com/rt2zz/redux-persist/issues/655#issuecomment-357700158). Anything that was possible in v4 is certainly achievable in v5 - PersistGate is just a convenience.

I dont want to make PersistGate more complex but its possible we could do one of the following:
1. create a new module `PersistGateAnimated` or something like that
2. expose an alternate api where instead of having a loading prop, it uses function children a la:
```js
<PersistGate persistor={persistor}>
  {(bootstrapped) => {
	// return fancy animation components here based on the value of bootstrapped
  }}
</PersistGate>
```

Open to suggestions, but it seems like 2 could be a good option that mirrors how react-router works.

**Comment by wachunei** [comment]
I kinda like the idea of option 2, but in that case, where the main components of the app go? I think is a little bit confusing.

In the same direction, we could achieve something like `loading` but with a render prop.
```jsx
  <Provider store={store}>
    <PersistGate
      persistor={persistor}
      loading={({ hydrated, liftGate, ...otherProps }) => <MyAnimatedComponent hydrated={...} liftGate={...} />}
    >
      <MyAppGoesHere />
    </PersistGate>
  </Provider>
```
I this case MyAnimatedComoponent can start an animation on hydration and lift gate as it ends.

PS: I really have no deep understanding of how possible to do is this, but I can dive in if this goes through

**Comment by rt2zz** [comment]
@wachunei well again taking the react router analogy option 2 would work like this:
```js
<PersistGate persistor={persistor}>
  {(bootstrapped) => {
     return [
        <AnimatedLoader visible={!bootstrapped} />,
        bootstrapped && <MyAppGoesHere />
     ]
  }}
</PersistGate>
```

i.e. it puts the responsibility for rendering the loader and main app into the hands of the implementor, but the common pattern would be basically `bootstrapped && <MyAppGoesHere />`

The approach you describe here: https://github.com/rt2zz/redux-persist/issues/655#issuecomment-362416964 is problematic to me because a) it does not solve as many use cases and b) it overloads the meaning of loading prop which may confuse users.

If I can elaborate on (a) consider this use case where you want to initialize a component to get some heavy lifting done immediately but still need to know when boostrap is complete to do additional work:
```js
<PersistGate persistor={persistor}>
  {(bootstrapped) => {
	return <MyAppGoesHere bootstrapped={bootstrapped} />
  }}
</PersistGate>
```

Of course this is all somewhat straight forward to replicate using a custom component which listens to the persistor, but I like that this pattern preserves the onBeforeLift pattern.

**Comment by wachunei** [comment]
I get it now, I'd like to contribute on this

**Comment by wachunei** [comment]
@rt2zz I'm sorry to bother with this question, but I was going to begin working on this when I ran into Metro Bundler does not support symlinks inside `./node_modules` (I was using [`yarn link`](https://yarnpkg.com/lang/en/docs/cli/link/) to link my local branch of `redux-persist` to a RN test app). 

So I've decided to move on to a `create-react-app` app. After linking the package I realized it has an entry point that only works after build (`lib`), but I started working on `src` files. What's your development setup? Am I doing something wrong or missing something in order to grab modules from `src` instead of built files?

Thanks!

**Comment by rt2zz** [comment]
@wachunei there are a few ways to do it. In my case with react native I always do one of the following (depending on the scale of changes):
1. in your app import from `src` (e.g. `import { persistStore } from 'redux-persisit/src'`) then edit the files in place and when you are done you copy the files back into your local git repo. 
2. use [wml](https://github.com/wix/wml) for create a "hardlink" alternative to yarn link.

Both options are a bit tedious :/

Or if you use create-react-app then yarn link should work *but* you need to be sure to build after every change. i.e. literally run `yarn build`. You can run the build in watch mode for convenience: ` yarn build:es --watch` but be sure to run the right build for your environment (i.e. es vs lib)

Now that I write this out I realize how frustratingly complex it is!

**Comment by wachunei** [comment]
I will try with those options, thanks!

Would it work to have an entry point that imports from src or lib depending on dev environment variable?

**Comment by rt2zz** [comment]
> Would it work to have an entry point that imports from src or lib depending on dev environment variable?

I am not sure how that would work - but open to suggestion. We use package.json module field to opt es users into the es build: https://github.com/rt2zz/redux-persist/blob/master/package.json#L6

**Comment by wachunei** [comment]
I spent last few hours trying to make this work, this is what I got: 

![animatedgate](https://user-images.githubusercontent.com/1024246/36080669-e0c46bac-0f71-11e8-966d-31dcec1fd9d2.gif)

The code for the end user would be basically changing this
```jsx
<Provider store={store}>
  <PersistGate persistor={persistor}>
      <App />
  </PersistGate>
</Provider>
```
to

```jsx
<Provider store={store}>
  <PersistGate persistor={persistor}>
    {bootstraped => (
      // custom component 
    )}
  </PersistGate>
</Provider>
```

in the previous gif case it was:
```jsx
<Provider store={store}>
  <PersistGate persistor={persistor}>
    {bootstraped => (
      <AnimatedGate bootstraped={bootstraped}>
        <App />
      </AnimatedGate>
    )}
  </PersistGate>
</Provider>
```

On the source the changes are 5 lines in `PersistGate` component, what do you think?

**Comment by rt2zz** [comment]
awesome, that looks perfect - mind opening a PR?

**Comment by isurugajasinghe** [comment]
@wachunei I used your code animatedgate.js but Image do not transparent. why is that  ?
<img width="606" alt="screen shot 2018-03-10 at 11 04 52 pm" src="https://user-images.githubusercontent.com/23732707/37253302-093ea5e4-2556-11e8-88e9-924027efaf07.png">
