### ISSUE TITLE
lazy load certain state

### ISSUE THREAD

**Issue by pke** [rt2zz/redux-persist#66]
I have some arrays in my state that I don't need at app start right away. I'd rather load them when I first need to display them. Does redux-persist support that?

**Comment by rt2zz** [comment]
It does not currently, but it could be added. the REHYDRATE action has no requirement to be complete, so we can potentially split the restoration process into 2+ actions. Do you have any api's in mind?

The one thing to consider is that we cannot start persisting until all state has been rehydrated, otherwise we risk overwriting the yet loaded state.

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.

**Comment by nishanBende** [comment]
@aguynamedben @pke @rt2zz I didn't know this issue existed, so I created a new one. I thought of an API in which we can have multiple PersistGate with a prop of which state to restore and delay rendering of that specific UI that needs that state.
https://github.com/rt2zz/redux-persist/issues/1094

**Comment by nishanBende** [comment]
Sometimes I hesitate to use this awesome library just because of this issue.
