### ISSUE TITLE
Dispatch function returns undefined after applying store enhancer

### ISSUE THREAD

**Issue by romanenko** [rt2zz/redux-persist#67]
Hello.

I've added store enhancer as the third argument to `createStore()`

```javascript
let middleware = applyMiddleware(thunk, promiseMiddleware(), routerMiddleware(history))

const store = createStore(rootReducer, initialState, compose(
  autoRehydrate(),
  middleware
))
```

And, after doing so, `dispatch(action)` calls began to return `undefined`.

Following the official Redux docs, `dispatch()` returns dispatched action (or return value from the middleware). It would be useful if store enhancer wouldn't break default behavior.

**Comment by romanenko** [comment]
After some investigation I began to get issue a bit better now. Return value from `dispatch(action)` calls are `undefined` because actions aren't dispatching immediately during store rehydration — they are getting queued by `bufferActions()`. 

I was implementing isomorphic app, and this behaviour caused problems, when I tried to wait for data-fetching from async actions to be done before rendering. I omitted `redux-persist` initialization in node environment and now my issues are gone.

But, still, maybe, we should return `action` from `dispatch()` after queueing its actual dispatching?

**Comment by rt2zz** [comment]
@romanenko generally redux-persist should be disabled on server since the model does not usually make sense for single use stores. That said I would like to best and most generically support all use cases. It may make sense to either turn off bufferActions or at least make it a configurable option. 

Because at the point that bufferActions has a chance to work is typically before other middleware has operated, we have no way to return the actual expected return value.

**Comment by rt2zz** [comment]
Ok, having thought more about this I am going to remove bufferActions in v3. I will cut a preliminary release soon.

**Comment by rt2zz** [comment]
v3 is available via `npm i --save redux-persist@next` **warning: may be highly unstable**
