### ISSUE TITLE
Persist state changes due to migration

### ISSUE THREAD

**Issue by chadmoller** [rt2zz/redux-persist#687]
From what I can tell, when I run a migration the state changes aren't persisted. I have to perform another action on the state to persist. 

Is there a way to persist the results of a migration when it updates something?

Thanks!

**Comment by rt2zz** [comment]
that would be fairly easy to achieve, we would simply need to call `persistoid.update(state)` before we return the rehydrated state here: https://github.com/rt2zz/redux-persist/blob/master/src/persistReducer.js#L131

with typical migrations this would never really matter since they are deterministic and would be safe to rerun. *but* technically a migration can do anything so perhaps your suggestion is the more conservative behavior.

**Comment by rt2zz** [comment]
this should be resolved by: https://github.com/rt2zz/redux-persist/pull/688

**Comment by chadmoller** [comment]
Awesome. Thanks for the fast response!!
