### ISSUE TITLE
Doesn't work with number object

### ISSUE THREAD

**Issue by incleaf** [rt2zz/redux-persist#95]
My codes were very simple like this:
```javascript
function reducer(state = 0, action) {
  switch (action.type) {
    case 'INCREMENT':
      return state + 1
    case 'DECREMENT':
      return state - 1
    default:
      return state
  }
}

const store = createStore(reducer, undefined, autoRehydrate())
persistStore(store)
```
Problem was persistStore function doesn't return number, returns just empty object.
So I wrapped my state like this:
```javascript
function reducer(state = {count: 0}, action) {
  switch (action.type) {
    case 'INCREMENT':
      return {count: state.count + 1};
    case 'DECREMENT':
      return {count: state.count - 1};
    default:
      return {count: state.count}
  }
}
```
and it works well. thanks for useful library ^^

**Comment by rt2zz** [comment]
@incleaf is this your top level reducer? that is correct redux-persist only works with state that is an object. Most people use combineReducers hence this is usually the case. 

Supporting top level non-object state is actually non-trivial because a lot of redux-persist works on a per-sub-reducer basis (e.g. transforms).

**Comment by incleaf** [comment]
My reducer is from redux example. and yeah it was my root reducer.

**Comment by rt2zz** [comment]
we should definitely warn/error if state is not plain

**Comment by rt2zz** [comment]
persistor will now warn when incompatible state: https://github.com/rt2zz/redux-persist/blob/master/src/createPersistor.js#L32 👍
